version: '1.0.{build}'
image: Visual Studio 2017

branches:
  only:
    - master

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./MediatR.Plugins/MediatR.Plugins.csproj --verbosity m
  - cmd: dotnet test

deploy:
  provider: NuGet
  api_key:
    secure: SZKU6CWMvIkMnkBBW2pH27cyloHzca15AJ85mjk07gmUjhDU1Y33dlccSnfVQNJL
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only