version: '1.0.{build}'
image: Visual Studio 2017

branches:
  only:
    - master

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/src.csproj --verbosity m

deploy:
  provider: NuGet
  api_key:
    secure: $(NUGET_TOKEN)
  skip_symbols: false
  artifact: /.*\.nupkg/